export const data = [
    {
        id: "Web Development",
        head1: "Concepts/Misconcepts",
        head2: "Tools",
        head3: "Extra Stuffs->For Intermediates",
        img: "./img/about.jpg",
    },
    {
        id: "MisConcepts",
        head1: "Learn Libraries",
        head2: "Learn Frontend and Backend at once",
        head3: "",
        img: "./img/webtool1.webp",
    },
    {
        id: "Concepts",
        head1: "Learn Minimal Tools",
        head2: "No Libraries & Framework Required",
        head3: "First Only Learn Frontend",
        img: "./img/web6.jpg",
    },
    {
        id: "Tools",
        head1: "HTML(5)->80%",
        head2: "CSS(3)->30%",
        head3: "Vanilla JavaScript->50%",
        img: "./img/webtool2.webp",
    },
    {
        id: "Make Small Projects",
        head1: "Using HTML Only",
        head2: "Using HTML and CSS Only",
        head3: "Using HTML and Javascript",
        img: "./img/web4.webp",
    },
    {
        id: "Advanced Tools",
        head1: "Bootstrap",
        head2: "SASS",
        head3: "ReactJs",
        img: "./img/webtool2.webp",
    },
    {
        id: "More Tools",
        head1: "Backend",
        head2: "PHP is Your Best Beginners Friend",
        head3: "",
        img: "./img/web3.webp",
    },
    {
        id: "Essential Tools",
        head1: "Code Editor->VSCode",
        head2: "Github->Free",
        head3: "CPanel->Paid",
        img: "./img/code4.jpg",
    },
    {
        id: "Powerful People Develop Powerful Languages",
        head1: "",
        head2: "",
        head3: "",
        img: "./img/suraj.jpg",
    },
    {
        id: "Powerful People Make Languages Powerful",
        head1: "",
        head2: "",
        head3: "",
        img: "./img/surajprofile.jpg",
    },
    {
        id: "Links of Social Media",
        head1: "Facebook Page -> BiT",
        head2: "Youtube Channel -> Bit Techno ",
        head3: "LinkedIn -> Suraj Keshari",
        img: "./img/logo2.jpg",
    },
    {
        id: "Made by the Web Developer Suraj Keshari Thank You",
        head1: "",
        head2: "",
        head3: "",
        img: "./img/logo2.jpg",
    },
    {
        id: "Questions???",
        head1: "THE END",
        head2: "",
        head3: "",
        img: "./img/quiz2.jpg",
    }
];